-- MCount schema. Timestamps are epoch milliseconds to match the API.

create table quizzes (
  id text primary key,
  name text not null,
  duration_seconds integer not null default 30,
  answer_seconds integer not null default 5,
  created_at bigint not null
);

-- quiz_id foreign keys cascade on update so changing a quiz slug is a single UPDATE.
create table questions (
  id bigint generated by default as identity primary key,
  quiz_id text not null references quizzes(id) on delete cascade on update cascade,
  position integer not null,
  text text not null,
  answer text not null default ''
);
create index idx_questions_quiz on questions(quiz_id, position);

create table runs (
  id text primary key,
  quiz_id text not null references quizzes(id) on delete cascade on update cascade,
  name text not null,
  status text not null default 'draft' check (status in ('draft', 'published', 'completed')),
  randomized boolean not null default false,
  question_order jsonb not null default '[]', -- array of question ids in run order
  created_at bigint not null,
  published_at bigint,
  completed_at bigint
);
create index idx_runs_quiz on runs(quiz_id);
-- Only one published run per quiz.
create unique index idx_runs_one_published on runs(quiz_id) where status = 'published';

create table participants (
  id text primary key,
  run_id text not null references runs(id) on delete cascade,
  name text not null,
  score integer not null default 0,
  created_at bigint not null
);
create index idx_participants_run on participants(run_id);

-- The app connects as the table owner, which bypasses RLS. Enabling RLS with no
-- policies blocks the public Supabase Data API (anon/authenticated keys).
alter table quizzes enable row level security;
alter table questions enable row level security;
alter table runs enable row level security;
alter table participants enable row level security;
