-- Vocabulary flashcard decks built from dictionaryapi.dev lookups.

create table decks (
  id text primary key,                 -- slug, like quizzes
  name text not null,
  description text not null default '',
  max_senses integer not null default 3 check (max_senses between 1 and 10),
  status text not null default 'draft' check (status in ('draft', 'published')),
  published_cards jsonb,               -- frozen copy served to students
  created_at bigint not null,
  updated_at bigint not null,          -- last draft edit
  published_at bigint
);

create table deck_words (
  id bigint generated by default as identity primary key,
  deck_id text not null references decks(id) on delete cascade on update cascade,
  position integer not null,
  word text not null,
  lookup_status text not null default 'pending'
    check (lookup_status in ('pending', 'ready', 'not_found', 'error')),
  phonetic text,
  audio_url text,
  senses jsonb not null default '[]'   -- picked: [{partOfSpeech, definition, example, synonyms, custom}]
);
create unique index idx_deck_words_unique on deck_words(deck_id, lower(word));
create index idx_deck_words_deck on deck_words(deck_id, position);
create index idx_deck_words_pending on deck_words(deck_id) where lookup_status = 'pending';

-- Raw dictionary responses, shared across decks so a word is fetched once.
create table dictionary_cache (
  word text primary key,               -- lowercased
  http_status integer not null,
  response jsonb,
  fetched_at bigint not null
);

alter table decks enable row level security;
alter table deck_words enable row level security;
alter table dictionary_cache enable row level security;
