-- Pronunciation recordings copied from dictionaryapi.dev, served by the app itself
-- (the source host is too slow to play from on click). Shared across decks by source URL.
create table audio_files (
  id bigint generated by default as identity primary key,
  source_url text not null unique,
  content_type text not null,
  byte_size integer not null,
  data bytea not null,
  fetched_at bigint not null
);
alter table audio_files enable row level security;

-- audio_url stays the source URL the admin chose; audio_id is the stored copy.
alter table deck_words
  add column audio_id bigint references audio_files(id) on delete set null,
  add column audio_error text;

-- Words whose chosen recording still needs downloading.
create index idx_deck_words_audio_pending on deck_words(deck_id)
  where audio_url is not null and audio_id is null and audio_error is null;
